# -*- coding: utf-8 -*-
"""ShopBuddy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J2kDdCpiCmGySyy1e1PYarNePcWyYEuG
"""

import streamlit as st
import os
from google import genai
from google.genai.types import GenerateContentConfig, Tool, GoogleSearch
from google.genai.errors import APIError

# ===========================
# 1. SETUP & CONFIGURATION
# ===========================

st.set_page_config(page_title="Product IQ: Agentic Shopper", page_icon="🧠", layout="wide")

# --- Custom CSS for Badges & UI ---
st.markdown("""
<style>
    .badge {
        display: inline-block;
        padding: 0.25em 0.6em;
        font-size: 0.85em;
        font-weight: 700;
        line-height: 1;
        text-align: center;
        white-space: nowrap;
        vertical-align: baseline;
        border-radius: 0.25rem;
        margin-right: 5px;
        margin-bottom: 5px;
    }
    .badge-trust { background-color: #28a745; color: white; }
    .badge-warning { background-color: #ffc107; color: black; }
    .badge-danger { background-color: #dc3545; color: white; }
    .badge-info { background-color: #17a2b8; color: white; }
    .report-box { border: 1px solid #ddd; padding: 20px; border-radius: 10px; background-color: #f9f9f9; }
</style>
""", unsafe_allow_html=True)

# --- SECRETS MANAGEMENT ---
# Attempt to retrieve API key from environment variables (Colab secrets are injected here)
api_key = os.getenv("GEMINI_API_KEY")

if not api_key:
    # If not found in environment, prompt user via Streamlit sidebar
    with st.sidebar:
        st.header("🔑 Configuration")
        api_key_input = st.text_input("Gemini API Key", type="password")
        if api_key_input:
            api_key = api_key_input
            os.environ["GEMINI_API_KEY"] = api_key # Store in env for consistent access
        else:
            st.warning("⚠️ API Key needed to run.")
            st.stop()

# Configure the genai library with the obtained API key
if not api_key:
    st.error("API Key not found or provided.")
    st.stop()

try:
    # Pass api_key to the Client constructor
    client = genai.Client(api_key=api_key)
except Exception as e:
    st.error(f"Client Init Error: {e}")
    st.stop()

MODEL_ID = "gemini-3-pro-preview"

# --- SESSION STATE INITIALIZATION ---
if "research_data" not in st.session_state:
    st.session_state.research_data = None
if "general_report" not in st.session_state:
    st.session_state.general_report = None
if "messages" not in st.session_state:
    st.session_state.messages = []
if "product_name" not in st.session_state:
    st.session_state.product_name = ""

# ===========================
# 2. AGENT PERSONAS (The Brains)
# ===========================

# --- Agent 1: The Deep Hunter (Research) ---
RESEARCHER_INSTRUCTION = """
ROLE: You are the \"Product Intelligence Engine\". You do not just search; you investigate.
GOAL: Gather deep, conflict-aware data for {product_name} AND its top 3 competitors.

MANDATORY DATA POINTS TO FETCH:
1.  **Market Status:** Is it Limited Edition? Discontinued? What are the sales trends/popularity in major regions (US, EU, Asia)?
2.  **The \"Hidden Gotchas\":** Find maintenance costs, subscription fees, accessory requirements, and common repair issues after 6 months.
3.  **Fake Review Detection:** Scan for patterns—disparity between \"professional\" and \"user\" reviews, or floods of 5-star vague reviews.
4.  **Competitor Intelligence:** Find 2-3 direct rivals. Compare Price vs. Performance.
5.  **Technical Specs:** The hard numbers (dimensions, battery life, materials).
6.  **Price Intelligence:** Current street price, MSRP, and discount history.

OUTPUT:
Raw, detailed, unsummarized notes. Cite every claim.
"""

# --- Agent 2: The Unbiased Analyst (General Report) ---
EDITOR_INSTRUCTION = """
ROLE: You are the \"Transparent Shopping Consultant\". You hate industry jargon and sponsored bias.
GOAL: Create a robust, easy-to-read Master Report for {product_name}.

INPUT: Use the provided Raw Research Data.

STRUCTURE & RULES:
1.  **Visuals:** Start with .
2.  **Trust Badges:** At the top, assign badges based on data:
    - \"✅ High Reliability\" (if few defects found)
    - \"⚠️ Fake Review Risk\" (if suspicious patterns found)
    - \"🏆 Best Value\" (if beats competitors)
3.  **The \"0-Second Summary\":** A 3-bullet TL;DR.
4.  **Decision Stress Eliminator:**
    - **\"The Main Pick\":** {product_name} (Why?)
    - **\"The Budget Alternative\":** (Name a cheaper rival found in data)
    - **\"The Performance Upgrade\":** (Name a better rival found in data)
5.  **Long-Term Ownership:** A dedicated section on \"Life with this product after 1 year\" (Maintenance, wear & tear).
6.  **Transparency Box:** Explicitly state: \"We found X conflicting data points...\" or \"This recommendation is based on...\"
7.  **Tone:** Empowering, clear, direct. No fluff.

OUTPUT FORMAT: Clean Markdown.
"""

# --- Agent 3: The Personalizer (User Profile) ---
PERSONALIZER_INSTRUCTION = """
ROLE: You are a hyper-personalized Sales Engineer.
GOAL: Re-evaluate {product_name} specifically for the USER'S PROFILE.

INPUT:
1. General Research Data (Context)
2. User's \"About Me\" (Profile)

TASK:
1.  **Match/Mismatch:** Does this product fit their specific lifestyle? (e.g., \"You said you hate noise, but this unit is 60dB...\")
2.  **The Verdict:** \"YES, BUY IT\" or \"NO, AVOID IT\". Be decisive.
3.  **Usage Simulation:** \"Here is how this fits into your daily routine...\"
4.  **Do Not Buy List:** If it fails their constraints, create a \"Why this is on your Blacklist\".

OUTPUT: A short, punchy personal letter to the user.
"""

# ===========================
# 3. HELPER FUNCTIONS
# ===========================

def run_research(product_name):
    """Step 1: Deep Web Search"""
    config = GenerateContentConfig(
        tools=[Tool(google_search=GoogleSearch())],
        system_instruction=RESEARCHER_INSTRUCTION.format(product_name=product_name),
        temperature=0.3
    )
    prompt = f"""
    Investigate {product_name}.
    - Compare with 3 rivals.
    - Find long-term reliability issues.
    - Check for fake review patterns.
    - Get sales trends and availability status.
    """
    response = client.models.generate_content(
        model=MODEL_ID,
        contents=prompt,
        config=config
    )
    return response

def generate_report(product_name, research_data):
    """Step 2: General Analysis"""
    config = GenerateContentConfig(
        system_instruction=EDITOR_INSTRUCTION.format(product_name=product_name),
        temperature=0.2
    )
    prompt = f"Research Data:\n{research_data}\n\nGenerate the Master Buying Guide."
    response = client.models.generate_content(
        model=MODEL_ID,
        contents=prompt,
        config=config
    )
    return response.text

def generate_personal_rec(product_name, research_data, user_profile):
    """Step 3: Personalization"""
    config = GenerateContentConfig(
        system_instruction=PERSONALIZER_INSTRUCTION.format(product_name=product_name),
        temperature=0.4
    )
    prompt = f"""
    Research Data: {research_data}

    User Profile: {user_profile}

    Generate a personalized recommendation letter.
    """
    response = client.models.generate_content(
        model=MODEL_ID,
        contents=prompt,
        config=config
    )
    return response.text

# ===========================
# 4. APP INTERFACE
# ===========================

st.title("🛍️ GoodBuy Guide")
st.markdown("### We Do the Homework. You Get the Best.")

# --- PHASE 1: INPUT ---
# We use a form so the page doesn't reload on every keystroke
with st.form("research_form"):
    product_input = st.text_input("What are you thinking of buying?", placeholder="e.g. Sony WH-1000XM5, Dyson Airwrap")
    submitted = st.form_submit_button("🔎 Show Me the Truth")

if submitted and product_input:
    st.session_state.product_name = product_input
    st.session_state.messages = [] # Reset chat
    st.session_state.general_report = None # Reset report

    status = st.status("🕵️ Initiating Deep Dive Agents...", expanded=True)

    try:
        # 1. Research
        status.write("🌍 **Hunting:** Scouring global markets, rivals, and forums...")
        research_response = run_research(product_input)
        st.session_state.research_data = research_response.text

        # 2. Report
        status.write("📊 **Analysing:** Balancing performance, quality, and value…")
        report_text = generate_report(product_input, st.session_state.research_data)
        st.session_state.general_report = report_text

        status.update(label="✅ Analysis Complete!", state="complete", expanded=False)

    except Exception as e:
        status.update(label="❌ Error", state="error")
        st.error(f"Agent Error: {e}")

# --- PHASE 2: DISPLAY REPORT ---
if st.session_state.general_report:
    st.divider()

    # 2.1 The Report
    st.markdown(st.session_state.general_report)

    # 2.2 Source Transparency
    with st.expander("🔍 View Raw Intelligence & Citations (Transparency Layer)"):
        st.info("We believe in showing our work. Here is the raw data our agents gathered.")
        st.text_area("Raw Data", st.session_state.research_data, height=200)

    st.divider()

    # --- PHASE 3: PERSONALIZATION ENGINE ---
    st.markdown("## 👤 The Private Investigator")
    st.markdown("Want to know if this product is **RIGHT for YOU**.")

    with st.container(border=True):
        st.markdown("#### Tell us about yourself")
        user_profile = st.text_area(
            placeholder="e.g. 'I am a student on a budget, I need this for coding and light gaming. I hate heavy laptops. I want it to last 4 years.'",
            help="The more details, the better the AI can simulate ownership for you."
        )

        if st.button("✨ Generate My Personal Verdict"):
            if not user_profile:
                st.warning("Please tell us a little about yourself first.")
            else:
                with st.spinner("🤖 Simulating your ownership experience..."):
                    personal_rec = generate_personal_rec(
                        st.session_state.product_name,
                        st.session_state.research_data,
                        user_profile
                    )
                    st.markdown("### 💌 Your Personal Verdict")
                    st.markdown(personal_rec)

    st.divider()

    # --- PHASE 4: AGENTIC CHAT ---
    st.markdown("## 💬 Ask Me Anything")
    st.caption(f"Want to know more about the **{st.session_state.product_name}** ?")

    # Display chat history
    for message in st.session_state.messages:
        with st.chat_message(message["role"]):
            st.markdown(message["content"])

    # Chat Input
    if prompt := st.chat_input(f"Ask about maintenance, rivals, or specific specs..."):
        # Add user message
        st.session_state.messages.append({"role": "user", "content": prompt})
        with st.chat_message("user"):
            st.markdown(prompt)

        # Generate Agent Response
        with st.chat_message("assistant"):
            with st.spinner("Thinking..."):
                chat_config = GenerateContentConfig(
                    system_instruction=f"You are an expert on {st.session_state.product_name}. Answer based on this research: {st.session_state.research_data}",
                )
                # Simple chat context construction
                chat_response = client.models.generate_content(
                    model=MODEL_ID,
                    contents=prompt,
                    config=chat_config
                )
                st.markdown(chat_response.text)

        # Add assistant message
        st.session_state.messages.append({"role": "assistant", "content": chat_response.text})